WX_OPEN_CONFIG = {
    'APP_ID': None,
    'APP_SECRET': None,
    'TOKEN': None,
    'ENCODING_AES_KEY': None
}

WX_OPEN_THIRD_CONFIG = {
    'COMPONENT_APP_ID': None,
    'COMPONENT_APP_SECRET': None,
    'COMPONENT_TOKEN': None,
    'COMPONENT_ENCODING_AES_KEY': None,
}
